### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by crecom86** [dheerajyadav54/expense#1]
Hello,

Please can you give a guide on how to install this expense manager.

Thanks

**Comment by dheerajyadav54** [comment]
Steps of Installation

1. Open the XAMPP website. Go to https://www.apachefriends.org/index.html in your computer's web browser.

2. Click XAMPP for Windows. It's a grey button near the bottom of the page.

3. Double-click the downloaded file.

4. Click Yes when prompted. This will open the XAMPP setup window.
You may have to click OK on a warning if you have User Account Control (UAC) activated on your computer.

5. Click Next. It's at the bottom of the setup window.

6. Select aspects of XAMPP to install.
By default, all attributes are included in your XAMPP installation.

7. Click Next. It's at the bottom of the window.

8. Select an installation location. Click OK. Doing so confirms your selected folder as your XAMPP installation location.

9. Click Next. You'll find it at the bottom of the page.

10. Uncheck the "Learn more about Bitnami" box, then click Next. The "Learn more about Bitnami" box is in the middle of the page.

11. Begin installing XAMPP. Click Next at the bottom of the window to do so. XAMPP will begin installing its files into the folder that you selected.

12. Click Finish when prompted. It's at the bottom of the XAMPP window.

13. Select a language. Check the box next to the American flag for English, or check the box next to the German flag for German.

14. Click Save.

For more information about installation please go through this link :- https://www.wikihow.com/Install-XAMPP-for-Windows
